# Generated by Django 4.1.4 on 2022-12-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
