# Generated by Django 4.1.4 on 2022-12-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_offer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
