# Generated by Django 4.1.4 on 2023-01-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_crop_image_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/crop_images', verbose_name='Foto'),
        ),
    ]
