# Generated by Django 4.1.4 on 2023-01-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_crop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, default='static/images/crop_images/no_image.png', null=True, upload_to='crop_images', verbose_name='Foto'),
        ),
    ]
