# Generated by Django 4.1.4 on 2023-01-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_crop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
    ]
