# Generated by Django 4.1.4 on 2023-01-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_crop_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='editing',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
