# Generated by Django 4.1.4 on 2023-02-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_remove_cart_items_cart_amount_cart_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
