# Generated by Django 4.1.4 on 2023-02-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_crop_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
        ),
    ]
